### ISSUE TITLE
set_smart_diacritics is adding useless accented characters

### ISSUE THREAD

**Issue by romainpoirier** [mundschenk-at/php-typography#149]
### Describe the bug
`set_smart_diacritics` is adding accented characters where this makes absolutely no sense, making this option useless.
né doesn't mean anything in French in a lot of context:

- Il est **né** → He is **born**
- Il **ne** veut **pas** → He does **not** want

While `ne` is most widely used, this setting is useless and must be disabled on French websites.

### To reproduce
1. Enable Typography with `set_smart_diacritics` set to `true`
2. Write `ne`
3. See text converted to `né`

**Comment by mundschenk-at** [comment]
It's not suitable for French because the default language (see `set_diacritic_language`) is `en-US`. Currently, the only two [languages supported are `en-US` and `de-DE`](https://github.com/mundschenk-at/php-typography/tree/main/src/diacritics). If you can provide a suitable JSON file for French, I'll gladly include it.
